### ISSUE TITLE
unable to access class function from JS on Xcode 9.1 swift 4 

### ISSUE THREAD

**Issue by yeshbourne** [XWebView/Sample#5]
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated) 
        
       wkwebController.add(self, name: "observe")
        wkwebConfiguration.userContentController = wkwebController
        
        self.wkWebView = WKWebView(frame: self.view.frame, configuration: wkwebConfiguration)
        self.view.addSubview(self.wkWebView)
        self.wkWebView.loadPlugin(self.rhylib!, namespace: "rhythm")

         let url = URL (string: rhyURL);
         let requestObj = URLRequest(url: url!, cachePolicy:       
         NSURLRequest.CachePolicy.useProtocolCachePolicy,timeoutInterval: 10.0);
        wkWebView.load(requestObj)
}

class RHYLib : NSObject {
  func screen(_ message: AnyObject?){
        print(message as! String)
    }
}

in JS trying to call window.rhythm.screen("Hello");

the object window.rhythm is attached to js below is the reference on console

{$channel: UserMessageHandler, $references: [], $lastRefID: 1, $retainObject: function, $releaseObject: function, …}

however the error i get on Xcode is 

Optional(Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=22072, WKJavaScriptExceptionMessage=TypeError: window.rhythm.screen is not a function. (In 'window.rhythm.screen("Hello")', 'window.rhythm.screen is undefined), WKJavaScriptExceptionColumnNumber=36, WKJavaScriptExceptionSourceURL=https://testweb.com/elements/elements.js, NSLocalizedDescription=A JavaScript exception occurred})

It was working on Xcode 8 swift 3.1

**Comment by yeshbourne** [comment]
the class self.rhylib is initialised

**Comment by yeshbourne** [comment]
Fixed it by adding @obj prefix before the method in plugin
